// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketMan.Infrastructure.Persistence.Context;

#nullable disable

namespace TicketMan.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TmDbContext))]
    partial class TmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketMan.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly?>("Time")
                        .HasColumnType("time");

                    b.Property<int?>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Manifest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Manifests");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("OfferId")
                        .HasColumnType("int");

                    b.Property<int?>("PriceTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("RowId")
                        .HasColumnType("int");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.HasIndex("PriceTypeId");

                    b.HasIndex("RowId");

                    b.HasIndex("SectionId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.PriceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PriceTypes");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Row", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("RowNumber")
                        .HasColumnType("int");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Rows");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsGeneralAdmission")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<int?>("OfferId")
                        .HasColumnType("int");

                    b.Property<int?>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.HasIndex("RowId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ManifestId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int?>("PriceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SeatId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PriceId");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Event", b =>
                {
                    b.HasOne("TicketMan.Domain.Entities.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Manifest", b =>
                {
                    b.HasOne("TicketMan.Domain.Entities.Venue", "Venue")
                        .WithMany("Manifests")
                        .HasForeignKey("VenueId");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Offer", b =>
                {
                    b.HasOne("TicketMan.Domain.Entities.Event", "Event")
                        .WithMany("Offers")
                        .HasForeignKey("EventId");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Price", b =>
                {
                    b.HasOne("TicketMan.Domain.Entities.Offer", "Offer")
                        .WithMany("Prices")
                        .HasForeignKey("OfferId");

                    b.HasOne("TicketMan.Domain.Entities.PriceType", "PriceType")
                        .WithMany("Prices")
                        .HasForeignKey("PriceTypeId");

                    b.HasOne("TicketMan.Domain.Entities.Row", "Row")
                        .WithMany("Prices")
                        .HasForeignKey("RowId");

                    b.HasOne("TicketMan.Domain.Entities.Section", "Section")
                        .WithMany("Prices")
                        .HasForeignKey("SectionId");

                    b.Navigation("Offer");

                    b.Navigation("PriceType");

                    b.Navigation("Row");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Row", b =>
                {
                    b.HasOne("TicketMan.Domain.Entities.Section", "Section")
                        .WithMany("Rows")
                        .HasForeignKey("SectionId");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Seat", b =>
                {
                    b.HasOne("TicketMan.Domain.Entities.Offer", "Offer")
                        .WithMany("Seats")
                        .HasForeignKey("OfferId");

                    b.HasOne("TicketMan.Domain.Entities.Row", "Row")
                        .WithMany("Seats")
                        .HasForeignKey("RowId");

                    b.Navigation("Offer");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Section", b =>
                {
                    b.HasOne("TicketMan.Domain.Entities.Manifest", "Manifest")
                        .WithMany("Sections")
                        .HasForeignKey("ManifestId");

                    b.Navigation("Manifest");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("TicketMan.Domain.Entities.Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId");

                    b.HasOne("TicketMan.Domain.Entities.Price", "Price")
                        .WithMany("Tickets")
                        .HasForeignKey("PriceId");

                    b.HasOne("TicketMan.Domain.Entities.Seat", "Seat")
                        .WithMany("Tickets")
                        .HasForeignKey("SeatId");

                    b.HasOne("TicketMan.Domain.Entities.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId");

                    b.Navigation("Event");

                    b.Navigation("Price");

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.User", b =>
                {
                    b.HasOne("TicketMan.Domain.Entities.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Event", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Manifest", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Offer", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Price", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.PriceType", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Row", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Seat", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Section", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.User", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TicketMan.Domain.Entities.Venue", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Manifests");
                });
#pragma warning restore 612, 618
        }
    }
}
